sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js: '10'
jobs:
  include:
    - stage: test
      os: linux
      install: npm install
      script: npm run validate
      after_success: kcd-scripts travis-after-success
    - stage: test
      os: windows
      install: npm install
      script: npm run validate
branches:
  only: master
